{
 "title": "Pilot Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Pilot CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad{job=\"pilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pilot Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_maxHeap_bytes{job=\"pilot\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "base_memory_usedHeap_bytes{job=\"pilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pilot Classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total{job=\"pilot\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Pilot Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "base_thread_daemon_count{job=\"pilot\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "base_thread_count{job=\"pilot\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}